---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ekz-ekz-wego-test-flux
  namespace: wego-system
spec:
  interval: 5m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: ekz-ekz-wego-test-flux
  validation: client

